---

- name: Installation de php7.0
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - php7.0-apcu
    - php7.0-bz2
    - php7.0-cli
    - php7.0-curl
    - php7.0-enchant
    - php7.0-fpm
    - php7.0-gd
    - php7.0-geoip
    - php7.0-gmp
    - php7.0-igbinary
    - php7.0-imagick
    - php7.0-imap
    - php7.0-interbase
    - php7.0-intl
    - php7.0-json
    - php7.0-ldap
    - php7.0-mcrypt
    - php7.0-memcached
    - php7.0-mongodb
    - php7.0-msgpack
    - php7.0-mysql
    - php7.0-odbc
    - php7.0-opcache
    - php7.0-pgsql
    - php7.0-pspell
    - php7.0-readline
    - php7.0-recode
    - php7.0-redis
    - php7.0-snmp
    - php7.0-sqlite3
    - php7.0-sybase
    - php7.0-tidy
    - php7.0-xmlrpc
    - php7.0-xsl
    - snmp-mibs-downloader

- name: php cgi config
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='^cgi.fix_pathinfo=1$' replace='cgi.fix_pathinfo=0"' backup=no

- name: Activer les service au démérage (fpm)
  service: name=php7.0-fpm enabled=yes
